
stages:         
  - build
  - deploy

build-job:  
  image: docker
  stage: build
  services:
  - "docker:dind"
  script:
    - docker build -t tg-bot-weather:latest .

deploy-job:
  stage: deploy
  script:
    - docker-compose up -d

