- name: Install Gitlab
  hosts: all
  become: yes
  vars_files:
    - ansible-roles/group_vars/all.yml
  roles:
    - role: ansible-roles/prepare-server
      tags: prepare

    - role: ansible-roles/docker_install
      tags: docker    

    - role: ansible-roles/user-adding
      when: __user_vagrant is failed #or __user_vagrant.hosts|length == 0
      tags: user

    # - role: ansible-roles/gitlab-install
    #   tags: gitlab

