---
# tasks file for prepare-server

- name: Install Aptitude
  ansible.builtin.apt:
    name: aptitude
    state: latest
    update_cache: yes

- name: Update and upgrade apt packages
  ansible.builtin.apt:
    upgrade: yes
    update_cache: yes

- name: Set timezone to Eurpoe/Moscow
  ansible.builtin.timezone:
    name: Europe/Moscow

- name: Install Chrony
  ansible.builtin.apt:
    name: chrony
    state: latest
    update_cache: yes

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Install python and pip packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: "{{ state_present }}"
    update_cache: "{{ update_cache }}"
  with_items:
    - "{{ python_packages }}"
  when: item not in ansible_facts.packages
